### ISSUE TITLE
Renci.SshNet nuget latest update dependency resolve issue

### ISSUE THREAD

**Issue by madushann** [ritterim/silverpop-dotnet-api#63]
After updating Renci.SshNet to latest version, email function giving below dependancy error.

System.IO.FileLoadException: Could not load file or assembly 'Renci.SshNet, Version=2013.1.27.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Renci.SshNet, Version=2013.1.27.0, Culture=neutral, PublicKeyToken=null'
   at Silverpop.Client.SilverpopCommunicationsClient..ctor(TransactClientConfiguration configuration)
   at Silverpop.Client.TransactClient.<>c__DisplayClass5_0.<.ctor>b__0()
   at Silverpop.Client.TransactClient.SendMessage(TransactMessage message)

**Comment by kendaleiv** [comment]
Is a binding redirect missing? Are you seeing the issue on full framework, .NET Core 1.x, or .NET Core 2.x?

**Comment by madushann** [comment]
we are using .net 4.6.1, what happened was, we updated the Nuget
Renci.sshnet version to 2016.1.x then silverpop email sending failed by
giving the dependency error. i saw the referred version in nuspec file was,

<dependency id="SSH.NET" version="2013.1.27" />

**Comment by kendaleiv** [comment]
I was able to reproduce the issue you described with a new project by updating the SSH.NET package manually.

**Comment by kendaleiv** [comment]
[2.0.3](https://www.nuget.org/packages/silverpop-dotnet-api/2.0.4) now requires SSH.NET 2016.1.0. While the problem may resurface this should resolve it for now.

**Comment by kendaleiv** [comment]
[2.0.4](https://www.nuget.org/packages/silverpop-dotnet-api/2.0.4) now requires SSH.NET 2016.1.0. While the problem may resurface this should resolve it for now.
